BINANCE_API_KEY = ""
BINANCE_SECRET = ""

BYBIT_API_KEY = ""
BYBIT_SECRET = ""

# OKX credentials
OKX_API_KEY = ""
OKX_SECRET = ""
OKX_PASSWORD = ""

HYPERLIQUID_API_KEY = ""
HYPERLIQUID_SECRET_KEY = ""

# RabbitX credentials
RABBITX_API_KEY = ""
RABBITX_SECRET_KEY = ""
RABBITX_JWT_TOKEN = ""

# Database credentials
POSTGRES_HOST = ""
POSTGRES_PORT = ""
POSTGRES_DATABASE = ""
POSTGRES_USER = ""
POSTGRES_PASSWORD = ""
